export const SECTION_MAPPINGS: { [key: string]: string } = {
    // Common / General
    "Revelation": "Vahiy",
    "Belief": "İman",
    "Knowledge": "İlim",
    "Ablutions (Wudu')": "Abdest",
    "Bathing (Ghusl)": "Gusül",
    "Menstrual Periods": "Hayız",
    "Rubbing hands and feet with dust (Tayammum)": "Teyemmüm",
    "Prayers (Salat)": "Namaz",
    "Times of the Prayers": "Namaz Vakitleri",
    "Call to Prayers (Adhaan)": "Ezan",
    "Friday Prayer": "Cuma Namazı",
    "Fear Prayer": "Korku Namazı",
    "The Two Festivals (Eids)": "Bayram Namazları",
    "Witr Prayer": "Vitir Namazı",
    "Invoking Allah for Rain (Istisqaa)": "Yağmur Duası (İstiska)",
    "Eclipses": "Küsuf (Güneş Tutulması)",
    "Prostration During Recital of Qur'an": "Tilavet Secdesi",
    "Shortening the Prayers (At-Taqseer)": "Namazı Kısaltma (Seferi)",
    "Prayer at Night (Tahajjud)": "Teheccüd",
    "Virtues of Prayer at Masjid Makkah and Madinah": "Mescid-i Haram ve Mescid-i Nebevi'nin Fazileti",
    "Actions while Praying": "Namazda Yapılan İşler",
    "Forgetfulness in Prayer": "Sehiv Secdesi",
    "Funerals (Al-Janaa'iz)": "Cenazeler",
    "Obligatory Charity Tax (Zakat)": "Zekat",
    "Hajj (Pilgrimage)": "Hac",
    "`Umrah (Minor pilgrimage)": "Umre",
    "Pilgrims Prevented from Completing the Pilgrimage": "İhsar (Hacdan Alıkonulma)",
    "Penalty of Hunting while on Pilgrimage": "Hacda Avlanma Cezası",
    "Virtues of Madinah": "Medine'nin Fazileti",
    "Fasting": "Oruç",
    "Praying at Night in Ramadaan (Taraweeh)": "Teravih Namazı",
    "Virtues of the Night of Qadr": "Kadir Gecesi'nin Fazileti",
    "Retiring to a Mosque for Remembrance of Allah (I'tikaf)": "İtikaf",
    "Sales and Trade": "Alışveriş (Büyü)",
    "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)": "Selem Akdi",
    "Shuf'a": "Şuf'a (Öncelik Hakkı)",
    "Hiring": "İcare (Kiralama)",
    "Transferance of a Debt from One Person to Another (Al-Hawaala)": "Havale",
    "Kafalah": "Kefalet",
    "Representation, Authorization, Business by Proxy": "Vekalet",
    "Agriculture": "Ziraat (Müzaraa)",
    "Distribution of Water": "Su Dağıtımı (Müsakat)",
    "Loans, Payment of Loans, Freezing of Property, Bankruptcy": "Borçlanma ve İflas",
    "Khusoomaat": "Husumetler (Davalar)",
    "Lost Things Picked up by Someone (Luqatah)": "Buluntu Eşya (Lukata)",
    "Oppressions": "Mezalim (Haksızlıklar)",
    "Partnership": "Şirket",
    "Mortgaging": "Rehin",
    "Manumission of Slaves": "Köle Azad Etme",
    "Makaatib": "Mükatebe (Yazışma)",
    "Gifts": "Hibe",
    "Witnesses": "Şahitlikler",
    "Peacemaking": "Sulh",
    "Conditions": "Şartlar",
    "Wills and Testaments (Wasaayaa)": "Vasiyetler",
    "Fighting for the Cause of Allah (Jihaad)": "Cihad",
    "One-fifth of Booty to the Cause of Allah (Khumus)": "Humus (Ganimetin Beşte Biri)",
    "Jizyah and Mawaada'ah": "Cizye ve Muvadaa",
    "Beginning of Creation": "Yaratılışın Başlangıcı",
    "Prophets": "Peygamberler",
    "Virtues and Merits of the Prophet (pbuh) and his Companions": "Peygamberimiz ve Ashabının Faziletleri",
    "Companions of the Prophet": "Ashab-ı Kiram",
    "Merits of the Helpers in Madinah (Ansaar)": "Ensar'ın Faziletleri",
    "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)": "Megazi (Savaşlar)",
    "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))": "Tefsir",
    "Virtues of the Qur'an": "Kur'an'ın Faziletleri",
    "Wedlock, Marriage (Nikaah)": "Nikah",
    "Divorce": "Talak (Boşanma)",
    "Supporting the Family": "Nafaka",
    "Food, Meals": "Yiyecekler",
    "Sacrifice on Occasion of Birth (`Aqiqa)": "Akika",
    "Hunting, Slaughtering": "Av ve Kesim",
    "Al-Adha Festival Sacrifice (Adaahi)": "Kurban",
    "Drinks": "İçecekler",
    "Patients": "Hastalar",
    "Medicine": "Tıbb-ı Nebevi",
    "Dress": "Giyim (Libas)",
    "Good Manners and Form (Al-Adab)": "Edep",
    "Asking Permission": "İzin İsteme",
    "Invocations": "Dualar",
    "To make the Heart Tender (Ar-Riqaq)": "Rikak (Kalbi Yumuşatan Haller)",
    "Divine Will (Al-Qadar)": "Kader",
    "Oaths and Vows": "Yeminler ve Adaklar",
    "Expiation for Unfulfilled Oaths": "Yemin Kefareti",
    "Laws of Inheritance (Al-Faraa'id)": "Feraiz (Miras)",
    "Limits and Punishments set by Allah (Hudood)": "Hudud (Cezalar)",
    "Blood Money (Ad-Diyat)": "Diyetler",
    "Apostates": "Mürtedler",
    "(Statements made under) Coercion": "İkrah (Zorlama)",
    "Tricks": "Hileler",
    "Interpretation of Dreams": "Rüya Tabiri",
    "Afflictions and the End of the World": "Fitneler",
    "Judgments (Ahkaam)": "Ahkam (Hükümler)",
    "Wishes": "Temenniler",
    "Accepting Information Given by a Truthful Person": "Haber-i Vahid",
    "Holding Fast to the Qur'an and Sunnah": "Kitap ve Sünnete Sarılma",
    "Oneness, Uniqueness of Allah (Tawheed)": "Tevhid",

    // Muslim Specific
    "The Book of Faith": "İman Kitabı",
    "The Book of Purification": "Taharet Kitabı",
    "The Book of Menstruation": "Hayız Kitabı",
    "The Book of Prayers ": "Namaz Kitabı",
    "The Book of Mosques and Places of Prayer": "Mescidler ve Namaz Yerleri",
    "The Book of Prayer - Travellers": "Yolcu Namazı",
    "The Book of Prayer - Friday": "Cuma Namazı",
    "The Book of Prayer - Two Eids": "Bayram Namazı",
    "The Book of Prayer - Rain": "Yağmur Duası",
    "The Book of Prayer - Eclipses": "Küsuf Namazı",
    "The Book of Zakat": "Zekat Kitabı",
    "The Book of Fasting ": "Oruç Kitabı",
    "The Book of Pilgrimage": "Hac Kitabı",
    "The Book of Marriage": "Nikah Kitabı",
    "The Book of Suckling": "Süt Emzirme",
    "The Book of Divorce ": "Boşanma Kitabı",
    "The Book of Invoking Curses": "Lian",
    "The Book of Emancipation": "Itk (Azad Etme)",
    "The Book of Business Transactions": "Alışveriş (Buyu)",
    "The Book of Musaqah": "Müsakat",
    "The Book of the Rules of Inheritance": "Feraiz",
    "The Book of Gifts": "Hibeler",
    "The Book of Wills": "Vasiyetler",
    "The Book of Vows": "Adaklar",
    "The Book of Oaths": "Yeminler",
    "The Book of Oaths, Muharibun, Qisas (Retaliation), and Diyat (Blood Money)": "Kasame, Muharipler, Kısas ve Diyetler",
    "The Book of Legal Punishments": "Hudud",
    "The Book of Judicial Decisions": "Akdiye (Hükümler)",
    "The Book of Lost Property": "Lukata",
    "The Book of Jihad and Expeditions": "Cihad ve Siyer",
    "The Book on Government": "İmare (Yöneticilik)",
    "The Book of Hunting, Slaughter, and what may be Eaten": "Av ve Kesim",
    "The Book of Sacrifices": "Kurbanlar",
    "The Book of Drinks": "İçecekler",
    "The Book of Clothes and Adornment": "Giyim ve Süslenme",
    "The Book of Manners and Etiquette": "Edep",
    "The Book of Greetings": "Selam",
    "The Book of Poetry": "Şiir",
    "The Book of Vision": "Rüya",
    "The Book of Virtues": "Faziletler",
    "The Book of the Merits of the Companions": "Sahabenin Faziletleri",
    "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship": "Birr, Sıla ve Edep",
    "The Book of Destiny": "Kader",
    "The Book of Knowledge": "İlim",
    "The Book of Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness ": "Zikir, Dua, Tevbe ve İstiğfar",
    "The Book of Heart-Melting Traditions": "Rikak",
    "The Book of Repentance": "Tevbe",
    "Characteristics of The Hypocrites and Rulings Concerning Them": "Münafıkların Özellikleri",
    "The Book of Paradise, its Description, its Bounties and its Inhabitants": "Cennet ve Nimetleri",
    "The Book of Tribulations and Portents of the Last Hour": "Fitneler ve Kıyamet Alametleri",
    "The Book of Zuhd and Softening of Hearts ": "Zühd ve Rikak",
    "The Book of Commentary on the Qur'an": "Tefsir",

    // Ibn Majah Specific
    "The Book of the Sunnah": "Sünnet Kitabı",
    "The Book of Purification and its Sunnah": "Taharet ve Sünnetleri",
    "The Book of the Prayer": "Namaz Kitabı",
    "The Book of the Adhan and the Sunnah Regarding It": "Ezan ve Sünnetleri",
    "The Book on the Mosques and the Congregations": "Mescidler ve Cemaatler",
    "The Book of Establishing the Prayer and the Sunnah Regarding Them": "Namazın İkamesi",
    "The Book of Funerals": "Cenazeler",
    "The Book of Fasting": "Oruç",
    "The Book of Zakah": "Zekat",
    "The Book of Marriage": "Nikah",
    "The Book of Divorce": "Talak",
    "The Book of Expiation": "Kefaretler",
    // "The Book of Business Transactions" is duplicate, removing
    "The Book of Rulings": "Ahkam",
    // "The Book of Gifts" is duplicate, removing
    "The Book of Charity": "Sadakalar",
    "The Book of Pawning": "Rehin",
    "The Book of Preemption": "Şuf'a",
    // "The Book of Lost Property" is duplicate, removing
    "The Book of Manumission (of Slaves)": "Itk (Azad)",
    // "The Book of Legal Punishments" is duplicate, removing
    "The Book of Blood Money": "Diyetler",
    // "The Book of Wills" is duplicate, removing
    "The Book of Inheritance": "Miras",
    "The Book of Jihad": "Cihad",
    "The Book of Rituals": "Menasik (Hac)",
    // "The Book of Sacrifices" is duplicate, removing
    "The Book of Slaughtering": "Kesimler",
    "The Book of Hunting": "Avcılık",
    "The Book of Food": "Yiyecekler",
    // "The Book of Drinks" is duplicate, removing
    "The Book of Medicine": "Tıp",
    "The Book of Dress": "Giyim",
    "The Book of Etiquette": "Edep",
    "The Book of Supplication": "Dua",
    "The Book of the Interpretation of Dreams": "Rüya Tabiri",
    "The Book of Tribulations": "Fitneler",
    "The Book of Zuhd": "Zühd",

    // Tirmidhi & Others
    "The Book on Purification": "Taharet Kitabı",
    "The Book on Salat (Prayer)": "Namaz Kitabı",
    "The Book on Al-Witr": "Vitir Kitabı",
    "The Book on the Day of Friday": "Cuma Günü Kitabı",
    "The Book on the Two Eids": "Bayram Namazları",
    "The Book on Traveling": "Yolculuk Kitabı",
    "The Book on Zakat": "Zekat Kitabı",
    "The Book on Fasting": "Oruç Kitabı",
    "The Book on Hajj": "Hac Kitabı",
    "The Book on Jana''iz (Funerals)": "Cenaze Kitabı",
    "The Book on Marriage": "Nikah Kitabı",
    "The Book on Suckling": "Süt Emzirme",
    "The Book on Divorce and Li'an": "Talak ve Lian",
    "The Book on Business": "Ticaret Kitabı",
    "The Book on Judgements From The Messenger of Allah": "Ahkam (Hükümler)",
    "The Book on Blood Money": "Diyetler",
    "The Book on Legal Punishments (Al-Hudud)": "Hudud (Cezalar)",
    "The Book on Hunting": "Avcılık",
    "The Book on Sacrifices": "Kurbanlar",
    "The Book on Vows and Oaths": "Yeminler ve Adaklar",
    "The Book on Military Expeditions": "Siyer ve Savaşlar",
    "The Book on Virtues of Jihad": "Cihadın Faziletleri",
    "The Book on Jihad": "Cihad",
    "The Book on Clothing": "Giyim",
    "The Book on Food": "Yiyecekler",
    "The Book on Drinks": "İçecekler",
    "Chapters on Righteousness And Maintaining Good Relations With Relatives": "Birr ve Sıla",
    "Chapters on Medicine": "Tıp",
    "Chapters On Inheritance": "Miras",
    "Chapters On Wasaya (Wills and Testament)": "Vasiyetler",
    "Chapters On Wala' And Gifts": "Vela ve Hibeler",
    "Chapters On Al-Qadar": "Kader",
    "Chapters On Al-Fitan": "Fitneler",
    "Chapters On Dreams": "Rüyalar",
    "Chapters On Witnesses": "Şahitlikler",
    "Chapters On Zuhd": "Zühd",
    "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'": "Kıyamet ve Rikak",
    "Chapters on the description of Paradise": "Cennetin Tasviri",
    "The Book on the Description of Hellfire": "Cehennemin Tasviri",
    "The Book on Faith": "İman Kitabı",
    "Chapters on Knowledge": "İlim",
    "Chapters on Seeking Permission": "İzin İsteme",
    "Chapters on Manners": "Edep",
    "Chapters on Parables": "Meseller",
    "Chapters on The Virtues of the Qur'an": "Kur'an'ın Faziletleri",
    "Chapters on Recitation": "Kıraat",
    "Chapters on Tafsir": "Tefsir",
    "Chapters on Supplication": "Dua",
    "Chapters on Virtues": "Faziletler",

    // Fallback for common words
    "Book": "Kitap",
    "Chapter": "Bölüm",
    "Introduction": "Giriş",
    "Preface": "Önsöz"
};

export const translateSection = (englishName: string): string => {
    if (!englishName) return '';

    // 1. Direct match
    if (SECTION_MAPPINGS[englishName]) {
        return SECTION_MAPPINGS[englishName];
    }

    // 2. Try to find a partial match or clean up
    let cleanName = englishName;

    // Remove common prefixes
    const prefixes = [
        /^The Book of\s+/,
        /^The Book on\s+/,
        /^Chapters on\s+/,
        /^Chapters regarding\s+/,
        /^Book of\s+/
    ];

    for (const prefix of prefixes) {
        cleanName = cleanName.replace(prefix, '');
    }

    cleanName = cleanName.trim();

    // Check mapping again with cleaned name
    if (SECTION_MAPPINGS[cleanName]) {
        return SECTION_MAPPINGS[cleanName];
    }

    // 3. Keyword matching (Fallback)
    const keywords: { [key: string]: string } = {
        "Prayer": "Namaz",
        "Salat": "Namaz",
        "Zakat": "Zekat",
        "Fasting": "Oruç",
        "Hajj": "Hac",
        "Jihad": "Cihad",
        "Marriage": "Nikah",
        "Divorce": "Talak",
        "Food": "Yiyecekler",
        "Drinks": "İçecekler",
        "Clothing": "Giyim",
        "Dress": "Giyim",
        "Purification": "Taharet",
        "Inheritance": "Miras",
        "Wills": "Vasiyetler",
        "Funerals": "Cenazeler",
        "Quran": "Kur'an",
        "Qur'an": "Kur'an",
        "Tafsir": "Tefsir",
        "Dreams": "Rüyalar",
        "Judgements": "Hükümler",
        "Faith": "İman",
        "Knowledge": "İlim",
        "Virtues": "Faziletler",
        "Supplication": "Dua",
        "Paradise": "Cennet",
        "Hell": "Cehennem",
        "Resurrection": "Kıyamet",
        "Prophets": "Peygamberler",
        "Companions": "Sahabeler"
    };

    for (const [key, value] of Object.entries(keywords)) {
        if (cleanName.includes(key)) {
            return value; // Return the keyword translation if found
        }
    }

    return englishName; // Return original if no match found
};
